name: darwin.kerluke
description: grid-enabled
version: 0.0.1
author: t07ynooh.eowjsigt@mzvdups9.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: darwinkerluke
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-11-21 22:48:30'
pipelines:
  pipelines/Rey_Ortiz_IIJuan_FortharoadJerald_Herzog:
    name: Rey_Ortiz_IIJuan_FortharoadJerald_Herzog
    description: null
    author: t07ynooh.eowjsigt@mzvdups9.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-11-21 22:48:30'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-11-21 22:48:30'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-11-21T22:48:30.529724Z'
  name: plibMaven
  version: 8.16.0-SNAPSHOT
  id: '1412678028'
  createdAt: '2025-11-21T22:48:30.529724Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
